package Modelo;
// Generated 18-dic-2020 16:35:14 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private int id;
     private TipoArea tipoArea;
     private Edificio edificio;
     private String nombre;
     private Set solicituds = new HashSet(0);

    public Area() {
    }

	
    public Area(int id, TipoArea tipoArea, Edificio edificio, String nombre) {
        this.id = id;
        this.tipoArea = tipoArea;
        this.edificio = edificio;
        this.nombre = nombre;
    }
    public Area(int id, TipoArea tipoArea, Edificio edificio, String nombre, Set solicituds) {
       this.id = id;
       this.tipoArea = tipoArea;
       this.edificio = edificio;
       this.nombre = nombre;
       this.solicituds = solicituds;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public TipoArea getTipoArea() {
        return this.tipoArea;
    }
    
    public void setTipoArea(TipoArea tipoArea) {
        this.tipoArea = tipoArea;
    }
    public Edificio getEdificio() {
        return this.edificio;
    }
    
    public void setEdificio(Edificio edificio) {
        this.edificio = edificio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set solicituds) {
        this.solicituds = solicituds;
    }




}


