package Modelo;
// Generated 18-dic-2020 16:35:14 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Articulo generated by hbm2java
 */
public class Articulo  implements java.io.Serializable {


     private int id;
     private TipoArticulo tipoArticulo;
     private String codigo;
     private Set articuloTieneSolicituds = new HashSet(0);

    public Articulo() {
    }

	
    public Articulo(int id, TipoArticulo tipoArticulo, String codigo) {
        this.id = id;
        this.tipoArticulo = tipoArticulo;
        this.codigo = codigo;
    }
    public Articulo(int id, TipoArticulo tipoArticulo, String codigo, Set articuloTieneSolicituds) {
       this.id = id;
       this.tipoArticulo = tipoArticulo;
       this.codigo = codigo;
       this.articuloTieneSolicituds = articuloTieneSolicituds;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public TipoArticulo getTipoArticulo() {
        return this.tipoArticulo;
    }
    
    public void setTipoArticulo(TipoArticulo tipoArticulo) {
        this.tipoArticulo = tipoArticulo;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Set getArticuloTieneSolicituds() {
        return this.articuloTieneSolicituds;
    }
    
    public void setArticuloTieneSolicituds(Set articuloTieneSolicituds) {
        this.articuloTieneSolicituds = articuloTieneSolicituds;
    }




}


