package Modelo;
// Generated 18-dic-2020 16:35:14 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int id;
     private Persona persona;
     private String correo;
     private int cargo;
     private int nip;
     private Set solicituds = new HashSet(0);

    public Cliente() {
    }
    
//    public Cliente(int id, String correo, int cargo, int nip) {
//        this.id = id;
//        this.correo = correo;
//        this.cargo = cargo;
//        this.nip = nip;
//    }

	
    public Cliente(int id, Persona persona, String correo, int cargo, int nip) {
        this.id = id;
        this.persona = persona;
        this.correo = correo;
        this.cargo = cargo;
        this.nip = nip;
    }
    public Cliente(int id, Persona persona, String correo, int cargo, int nip, Set solicituds) {
       this.id = id;
       this.persona = persona;
       this.correo = correo;
       this.cargo = cargo;
       this.nip = nip;
       this.solicituds = solicituds;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public int getCargo() {
        return this.cargo;
    }
    
    public void setCargo(int cargo) {
        this.cargo = cargo;
    }
    public int getNip() {
        return this.nip;
    }
    
    public void setNip(int nip) {
        this.nip = nip;
    }
    public Set getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set solicituds) {
        this.solicituds = solicituds;
    }




}


