package Modelo;
// Generated 18-dic-2020 16:35:14 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Edificio generated by hbm2java
 */
public class Edificio  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set areas = new HashSet(0);

    public Edificio() {
    }

	
    public Edificio(int id) {
        this.id = id;
    }
    public Edificio(int id, String nombre, Set areas) {
       this.id = id;
       this.nombre = nombre;
       this.areas = areas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getAreas() {
        return this.areas;
    }
    
    public void setAreas(Set areas) {
        this.areas = areas;
    }




}


