package Modelo;
// Generated 18-dic-2020 16:35:14 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Entrega generated by hbm2java
 */
public class Entrega  implements java.io.Serializable {


     private int id;
     private Personal personal;
     private String dia;
     private String entrega;
     private Set prestamos = new HashSet(0);

    public Entrega() {
    }

	
    public Entrega(int id, Personal personal) {
        this.id = id;
        this.personal = personal;
    }
    public Entrega(int id, Personal personal, String dia, String entrega, Set prestamos) {
       this.id = id;
       this.personal = personal;
       this.dia = dia;
       this.entrega = entrega;
       this.prestamos = prestamos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }
    public String getEntrega() {
        return this.entrega;
    }
    
    public void setEntrega(String entrega) {
        this.entrega = entrega;
    }
    public Set getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set prestamos) {
        this.prestamos = prestamos;
    }




}


