package Modelo;
// Generated 18-dic-2020 16:35:14 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Personal generated by hbm2java
 */
public class Personal  implements java.io.Serializable {


     private int id;
     private EstadoPersonal estadoPersonal;
     private Persona persona;
     private String contrasena;
     private Set entregas = new HashSet(0);

    public Personal() {
    }

	
    public Personal(int id, EstadoPersonal estadoPersonal, Persona persona, String contrasena) {
        this.id = id;
        this.estadoPersonal = estadoPersonal;
        this.persona = persona;
        this.contrasena = contrasena;
    }
    public Personal(int id, EstadoPersonal estadoPersonal, Persona persona, String contrasena, Set entregas) {
       this.id = id;
       this.estadoPersonal = estadoPersonal;
       this.persona = persona;
       this.contrasena = contrasena;
       this.entregas = entregas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public EstadoPersonal getEstadoPersonal() {
        return this.estadoPersonal;
    }
    
    public void setEstadoPersonal(EstadoPersonal estadoPersonal) {
        this.estadoPersonal = estadoPersonal;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Set getEntregas() {
        return this.entregas;
    }
    
    public void setEntregas(Set entregas) {
        this.entregas = entregas;
    }




}


