package Modelo;
// Generated 18-dic-2020 16:35:14 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {


     private PrestamoId id;
     private Solicitud solicitud;
     private Entrega entrega;
     private Devolucion devolucion;
     private String observaciones;
     private Date fecha;

    public Prestamo() {
    }

	
    public Prestamo(PrestamoId id, Solicitud solicitud, Entrega entrega, Devolucion devolucion, Date fecha) {
        this.id = id;
        this.solicitud = solicitud;
        this.entrega = entrega;
        this.devolucion = devolucion;
        this.fecha = fecha;
    }
    public Prestamo(PrestamoId id, Solicitud solicitud, Entrega entrega, Devolucion devolucion, String observaciones, Date fecha) {
       this.id = id;
       this.solicitud = solicitud;
       this.entrega = entrega;
       this.devolucion = devolucion;
       this.observaciones = observaciones;
       this.fecha = fecha;
    }
   
    public PrestamoId getId() {
        return this.id;
    }
    
    public void setId(PrestamoId id) {
        this.id = id;
    }
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }
    public Entrega getEntrega() {
        return this.entrega;
    }
    
    public void setEntrega(Entrega entrega) {
        this.entrega = entrega;
    }
    public Devolucion getDevolucion() {
        return this.devolucion;
    }
    
    public void setDevolucion(Devolucion devolucion) {
        this.devolucion = devolucion;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


