package Modelo;
// Generated 18-dic-2020 16:35:14 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Solicitud generated by hbm2java
 */
public class Solicitud  implements java.io.Serializable {


     private int id;
     private Cliente cliente;
     private Area area;
     private byte aceptada;
     private Set articuloTieneSolicituds = new HashSet(0);
     private Set prestamos = new HashSet(0);

    public Solicitud() {
    }

	
    public Solicitud(int id, Cliente cliente, Area area, byte aceptada) {
        this.id = id;
        this.cliente = cliente;
        this.area = area;
        this.aceptada = aceptada;
    }
    public Solicitud(int id, Cliente cliente, Area area, byte aceptada, Set articuloTieneSolicituds, Set prestamos) {
       this.id = id;
       this.cliente = cliente;
       this.area = area;
       this.aceptada = aceptada;
       this.articuloTieneSolicituds = articuloTieneSolicituds;
       this.prestamos = prestamos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }
    public byte getAceptada() {
        return this.aceptada;
    }
    
    public void setAceptada(byte aceptada) {
        this.aceptada = aceptada;
    }
    public Set getArticuloTieneSolicituds() {
        return this.articuloTieneSolicituds;
    }
    
    public void setArticuloTieneSolicituds(Set articuloTieneSolicituds) {
        this.articuloTieneSolicituds = articuloTieneSolicituds;
    }
    public Set getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set prestamos) {
        this.prestamos = prestamos;
    }




}


