package Modelo;
// Generated 18-dic-2020 16:35:14 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TipoArticulo generated by hbm2java
 */
public class TipoArticulo  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set articulos = new HashSet(0);

    public TipoArticulo() {
    }

	
    public TipoArticulo(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public TipoArticulo(int id, String nombre, Set articulos) {
       this.id = id;
       this.nombre = nombre;
       this.articulos = articulos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Set articulos) {
        this.articulos = articulos;
    }




}


